import 'package:talet_samak/core/models/user_entity.dart';

class User extends UserEntity {
  const User({
    super.id,
    super.nameFirst,
    super.nameLast,
    super.name,
    super.username,
    super.phone,
    super.email,
    super.isAvailable,
    super.vip,
    super.countryId,
    super.cityId,
    super.branchId,
    super.groupId,
    super.addressId,
    super.image,
    super.gender,
    super.genderName,
    super.birthDate,
    super.code,
    super.codeExpire,
    super.smsCode,
    super.smsCodeExpire,
    super.wallet,
    super.point,
    super.locale,
    super.latitude,
    super.longitude,
    super.polygon,
    super.active,
    super.lastActive,
    super.createdAt,
    super.updatedAt,
  });
  factory User.fromJson(Map<String, dynamic> json) {
    return User(
      id: json['id'],
      nameFirst: json['nameFirst'],
      nameLast: json['nameLast'],
      name: json['name'],
      username: json['username'],
      phone: json['phone'],
      email: json['email'],
      isAvailable: json['isAvailable'],
      vip: json['vip'],
      countryId: json['countryId'],
      cityId: json['cityId'],
      branchId: json['branchId'],
      groupId: json['groupId'],
      addressId: json['addressId'],
      image: json['image'],
      gender: json['gender'],
      genderName: json['genderName'],
      birthDate: json['birthDate'],
      code: json['code'],
      codeExpire: json['codeExpire'],
      smsCode: json['smsCode'],
      smsCodeExpire: json['smsCodeExpire'],
      wallet: json['wallet'],
      point: json['point'],
      locale: json['locale'],
      latitude: json['latitude'],
      longitude: json['longitude'],
      polygon: json['polygon'],
      active: json['active'],
      lastActive: json['lastActive'],
      createdAt: json['createdAt'],
      updatedAt: json['updatedAt'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'nameFirst': nameFirst,
      'nameLast': nameLast,
      'name': name,
      'username': username,
      'phone': phone,
      'email': email,
      'isAvailable': isAvailable,
      'vip': vip,
      'countryId': countryId,
      'cityId': cityId,
      'branchId': branchId,
      'groupId': groupId,
      'addressId': addressId,
      'image': image,
      'gender': gender,
      'genderName': genderName,
      'birthDate': birthDate,
      'code': code,
      'codeExpire': codeExpire,
      'smsCode': smsCode,
      'smsCodeExpire': smsCodeExpire,
      'wallet': wallet,
      'point': point,
      'locale': locale,
      'latitude': latitude,
      'longitude': longitude,
      'polygon': polygon,
      'active': active,
      'lastActive': lastActive,
      'createdAt': createdAt,
      'updatedAt': updatedAt,
    };
  }
}
